language: go
go_import_path: github.com/DUBXCOIN/go-dubxcoin
sudo: false
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      go: 1.8.3
      script:
        - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install fuse
        - sudo modprobe fuse
        - sudo chmod 666 /dev/fuse
        - sudo chown root:$USER /etc/fuse.conf
        - go run build/ci.go install

    - os: osx
      go: 1.9.x
      sudo: required
      script:
        - brew update
        - brew install caskroom/cask/brew-cask
        - brew cask install osxfuse
        - go run build/ci.go install
install:
  - go get golang.org/x/tools/cmd/cover
script:
  - go run build/ci.go install
